### ISSUE TITLE
[v1-rewrite] New UI: Detail view

### ISSUE THREAD

**Issue by roydejong** [roydejong/BeatSaberServerBrowser#52]
### TODO

- [x] New data model
- [x] Loading / idle states
- [x] Server status / level bar
- [x] Player count 
- [x] Details (tab)
- [x] Player list (tab)
- [x] Level history (tab)
- [x] Connect button (trigger)

### WIP

![image](https://user-images.githubusercontent.com/6772638/149364757-930bdf4a-86e5-44c8-b921-f26d667905c1.png)
